version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - goflow_network1
    env_file:
      - ./backend/.env.${ENV:-local}
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - goflow_network1
    volumes:
      - ./frontend:/app
  db:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - 3333:3306
    networks:
      - goflow_network1
    environment:
      MYSQL_DATABASE: ${DB_NAME:-goflow}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-root}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-root}
      TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
networks:
  goflow_network1: